language: erlang
install: true
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
env: PATH=$PATH:.
script: make test
otp_release:
  - 19.1
  - 19.0
  - 18.3
  - 18.0
  - 17.5
  # - 17.0
